//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Config.charcter
{
   
public partial class TbCharacterConfig
{
    private static TbCharacterConfig instance;
    public static TbCharacterConfig Instance
    {
        get
        {
            instance ??= Tables.Instance.TbCharacterConfig;
            return instance;
        }
    }

    private readonly Dictionary<int, charcter.CharacterConfig> _dataMap;
    private readonly List<charcter.CharacterConfig> _dataList;
    
    public TbCharacterConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, charcter.CharacterConfig>();
        _dataList = new List<charcter.CharacterConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            charcter.CharacterConfig _v;
            _v = charcter.CharacterConfig.DeserializeCharacterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, charcter.CharacterConfig> DataMap => _dataMap;
    public List<charcter.CharacterConfig> DataList => _dataList;

    public charcter.CharacterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public charcter.CharacterConfig Get(int key) => _dataMap[key];
    public charcter.CharacterConfig this[int key] => _dataMap[key];

    public void Resolve(Tables _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public void Clear()
    {
        instance = null;
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}