//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Config.common
{
public sealed partial class CommonConst :  Bright.Config.BeanBase 
{
    public CommonConst(ByteBuf _buf) 
    {
        TimeZone = _buf.ReadInt();
        HourOffset = _buf.ReadInt();
        PlayableMinAppVerion = _buf.ReadString();
        NewAppDownloadUrl = _buf.ReadString();
        PostInit();
    }

    public static CommonConst DeserializeCommonConst(ByteBuf _buf)
    {
        return new common.CommonConst(_buf);
    }

    public int TimeZone { get; private set; }
    public int HourOffset { get; private set; }
    public string PlayableMinAppVerion { get; private set; }
    public string NewAppDownloadUrl { get; private set; }

    public const int __ID__ = 136288405;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Tables _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TimeZone:" + TimeZone + ","
        + "HourOffset:" + HourOffset + ","
        + "PlayableMinAppVerion:" + PlayableMinAppVerion + ","
        + "NewAppDownloadUrl:" + NewAppDownloadUrl + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}