//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Config.common
{
public sealed partial class KeywordsFilterConfig :  Bright.Config.BeanBase 
{
    public KeywordsFilterConfig(ByteBuf _buf) 
    {
        Keyword = _buf.ReadString();
        PostInit();
    }

    public static KeywordsFilterConfig DeserializeKeywordsFilterConfig(ByteBuf _buf)
    {
        return new common.KeywordsFilterConfig(_buf);
    }

    public string Keyword { get; private set; }

    public const int __ID__ = -794649113;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Tables _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Keyword:" + Keyword + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}