//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Config.common
{
public sealed partial class L10nConfig :  Bright.Config.BeanBase 
{
    public L10nConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Text_l10n_key = _buf.ReadString(); Text = _buf.ReadString();
        PostInit();
    }

    public static L10nConfig DeserializeL10nConfig(ByteBuf _buf)
    {
        return new common.L10nConfig(_buf);
    }

    public int Id { get; private set; }
    public string Text { get; private set; }
    public string Text_l10n_key { get; }

    public const int __ID__ = 2092517224;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Tables _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Text = translator(Text_l10n_key, Text);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Text:" + Text + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}