//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Config.common
{
   
public partial class TbCommonConst
{
    private static TbCommonConst instance;
    public static TbCommonConst Instance
    {
        get
        {
            instance ??= Tables.Instance.TbCommonConst;
            return instance;
        }
    }


     private readonly common.CommonConst _data;
     public readonly common.CommonConst Data;

    public TbCommonConst(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = common.CommonConst.DeserializeCommonConst(_buf);
        Data = _data;
        PostInit();
    }


     public int TimeZone => _data.TimeZone;
     public int HourOffset => _data.HourOffset;
     public string PlayableMinAppVerion => _data.PlayableMinAppVerion;
     public string NewAppDownloadUrl => _data.NewAppDownloadUrl;

    public void Resolve(Tables _tables)
    {
        _data.Resolve(_tables);
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        _data.TranslateText(translator);
    }

    
    public void Clear()
    {
        instance = null;
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}