//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Config.common
{
   
public partial class TbSymbolsConfig
{
    private static TbSymbolsConfig instance;
    public static TbSymbolsConfig Instance
    {
        get
        {
            instance ??= Tables.Instance.TbSymbolsConfig;
            return instance;
        }
    }

    private readonly List<common.SymbolsConfig> _dataList;


    public TbSymbolsConfig(ByteBuf _buf)
    {
        _dataList = new List<common.SymbolsConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            common.SymbolsConfig _v;
            _v = common.SymbolsConfig.DeserializeSymbolsConfig(_buf);
            _dataList.Add(_v);
        }
        PostInit();
    }


    public List<common.SymbolsConfig> DataList => _dataList;


    public void Resolve(Tables _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public void Clear()
    {
        instance = null;
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}